### ISSUE TITLE
Issue with get_current_prices

### ISSUE THREAD

**Issue by avadiax** [madpilot/amberelectric.py#14]
Noticed that calling:

get_current_prices(site_id, previous=interval, resolution=resolution)

where interval > 6 results in the following error:

```
No match found when deserializing the JSON string into Interval with oneOf schemas: ActualInterval, CurrentInterval, ForecastInterval. Details: 1 validation error for ActualInterval
renewables
  ensure this value is less than or equal to 100 (type=value_error.number.not_le; limit_value=100), 3 validation errors for CurrentInterval
type
  must be one of enum values ('CurrentInterval') (type=value_error)
renewables
  ensure this value is less than or equal to 100 (type=value_error.number.not_le; limit_value=100)
estimate
  none is not an allowed value (type=type_error.none.not_allowed), 2 validation errors for ForecastInterval
type
  must be one of enum values ('ForecastInterval') (type=value_error)
renewables
  ensure this value is less than or equal to 100 (type=value_error.number.not_le; limit_value=100).
```

This only applies to "previous" and has no issue for "next". This issue happened about 3 hours ago.

**Comment by madpilot** [comment]
What state are you in? I'm guessing the renewable percentage for a previous interval was > 100 (which is very possible, for reasons)

**Comment by avadiax** [comment]
<Redacted>

That explains why, now that 30 minutes have passed, I increased the interval by 1 (so now interval=6 instead of interval=5) and it works. I am suspecting the 1:30 pm renewables is causing the issue. I check every 30 minutes.

**Comment by madpilot** [comment]
Yep, that's it - it was 101% at 13:30.

<img width="400" alt="image" src="https://github.com/user-attachments/assets/3a8b6702-1d5f-4b80-90aa-8fa200846227">

I'll need to update the OpenAPI specs and regenerate the code. I have to do some work on this over the weekend, so I'll try squeeze it in then.

**Comment by madpilot** [comment]
Fixed in https://github.com/madpilot/amberelectric.py/releases/tag/v2.0.4
